#!/bin/bash
# Script de ajuda rápida para o projeto

echo "=========================================="
echo "Modern Opensource Lakehouse - Comandos Úteis"
echo "=========================================="
echo ""
echo "1. Iniciar todos os serviços:"
echo "   docker compose up -d"
echo ""
echo "2. Ver logs:"
echo "   docker compose logs -f"
echo ""
echo "3. Executar queries de exemplo:"
echo "   docker compose exec duckdb python /app/scripts/example_queries.py"
echo ""
echo "4. Executar dbt:"
echo "   docker compose exec dbt dbt run"
echo ""
echo "5. Acessar MinIO Console:"
echo "   http://localhost:9001"
echo "   Usuário: admin"
echo "   Senha: minioadmin123"
echo ""
echo "6. Entrar no container DuckDB:"
echo "   docker compose exec duckdb bash"
echo ""
echo "7. Entrar no container dbt:"
echo "   docker compose exec dbt bash"
echo ""
echo "8. Parar todos os serviços:"
echo "   docker compose down"
echo ""
echo "9. Parar e remover volumes:"
echo "   docker compose down -v"
echo ""

